### ISSUE TITLE
add to Bower

### ISSUE THREAD

**Issue by bshack** [ryanseddon/H5F#65]
add bower config file and list in bower page search:

http://bower.io/search/

Searching for 'H5F'

returns this project:

https://github.com/dsheiko/HTML5-Form-Shim

**Comment by ryanseddon** [comment]
It's already on npm but if you wanna do a pr to put in on bower be my guest.

**Comment by jraller** [comment]
bower looks for h5f.js instead of h5f.min.js because the component.json is out of date and there is no .bower.json file
