### ISSUE TITLE
Non required fields with a placeholder attribute not working correctly

### ISSUE THREAD

**Issue by ryanseddon** [ryanseddon/H5F#7]
Bug report using H5F in Firefox 3.6.12. For a not required field using a placeholder text, the placeholder is not shown as the page is being loaded. Only the placeholders for required fields are shown on pageload. The placeholder text is (incorrectly) shown as soon as the field first receives focus. The placeholder text stays in the field (correct) when focus moves. When the not required input receives focus for the second time, the placeholder text is (correctly) removed. Cache is disabled, but seems involved. As soon as the placeholder once has been shown, a page reload maintains correct behaviour. Only after a shift+reload, the placeholder text is removed again.

Was first reported here http://www.thecssninja.com/javascript/h5f#comment-2251

**Comment by Speelb** [comment]
Unfortunately I still have the bug.
