### ISSUE TITLE
No validation in Safari 9

### ISSUE THREAD

**Issue by ms-studio** [ryanseddon/H5F#70]
I am looking for a way to make Safari behave well, and had some hope that the H5F library would be my solution... but alas the validation upon submission doesn’t work.

When testing [the demo](http://alistapart.com/d/forward-thinking-form-validation/enhanced_2.html) in Safari (9.0.1 under OSX 10.10.5), and just submitting the form empty, or with several empty required fields, the form gets submitted, without any message about filling out the missing fields being displayed.

**Comment by laander** [comment]
Same here, can't get it to react to anything, not even the `onSubmit` event fires

**Comment by ms-studio** [comment]
Finally I decided to use https://github.com/victorjonsson/jQuery-Form-Validator which his pretty awesome.
