### ISSUE TITLE
Could really use fieldset.checkValidity()

### ISSUE THREAD

**Issue by justinputney** [ryanseddon/H5F#71]
...to test subsets of a long form that's broken into multiple steps.
Thanks!

**Comment by amn** [comment]
Came here by a search. Not strictly related to H5F, but frankly, leaving out some sort of recursive validation out of a `fieldset` -- an element whose primary function is grouping form controls -- and just having it always assert `checkValidity() == true` is not as useful as it could have been with a recursive fieldset-localized validation.
